#!/bin/sh

commit_msg_file=$1

# 限制提交信息的长度
commit_msg=$(cat $commit_msg_file)
max_length=50
if [ $(echo "$commit_msg" | wc -m) -gt $max_length ]; then
    echo "Commit message is too long (maximum $max_length characters)."
    exit 1
fi

# 校验提交信息格式
commit_regex='^(feat|fix|chore|docs|style|refactor|test)(\/[A-Za-z0-9-]+)*: .{5,}$'
if ! echo "$commit_msg" | grep -iqE "$commit_regex"; then
    echo "Commit message format is incorrect. Use the format: '{type}: {message}'"
    exit 1
fi

exit 0